# Generated by Django 4.2.7 on 2025-06-19 12:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('invoice_date', models.DateField(verbose_name='Date de facture')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('payment_method', models.CharField(choices=[('cash', 'ESPÈCE'), ('check', 'CHÈQUE'), ('transfer', 'VIREMENT'), ('card', 'CARTE')], default='check', max_length=20, verbose_name='Mode de règlement')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='Chauffeur')),
                ('vehicle_registration', models.CharField(blank=True, max_length=20, verbose_name='Matricule véhicule')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Destination')),
                ('subtotal_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total HT')),
                ('tva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA')),
                ('timbre_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Timbre')),
                ('other_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Autres taxes')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('check', 'Chèque'), ('transfer', 'Virement'), ('card', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence')),
                ('description', models.CharField(max_length=500, verbose_name='Désignation')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire HT')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant HT')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='Facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit/Service')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
