# Generated by Django 4.2.7 on 2025-07-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modifié le'),
        ),
    ]
