# Generated by Django 4.2.7 on 2025-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceline_created_at_invoiceline_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='line_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'ajout"),
        ),
    ]
