# Generated by Django 4.2.7 on 2025-06-19 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^(\\d{3}-\\d{4})$')])),
            ],
            options={
                'verbose_name': 'cité',
                'verbose_name_plural': 'cités',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom/Raison sociale')),
                ('customer_type', models.CharField(choices=[('individual', 'Particulier'), ('company', 'Entreprise')], default='company', max_length=20, verbose_name='Type de client')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Adresse ligne 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activity', models.CharField(blank=True, max_length=200, verbose_name='Activité')),
                ('nis', models.CharField(blank=True, max_length=20, verbose_name='NIS')),
                ('rc', models.CharField(blank=True, max_length=20, verbose_name='RC')),
                ('art', models.CharField(blank=True, max_length=20, verbose_name='ART')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de crédit')),
                ('payment_terms', models.IntegerField(default=30, verbose_name='Délai de paiement (jours)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de remise (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.city', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
    ]
