# Generated by Django 4.2.7 on 2025-06-26 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant forfaitaire')),
                ('max_quantity_allowed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité maximale autorisée')),
                ('is_active', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], default='monthly', max_length=20, verbose_name='Cycle de facturation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abonnement produit',
                'verbose_name_plural': 'Abonnements produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='is_subscriber',
            field=models.BooleanField(default=False, verbose_name='Abonné avec offres'),
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité utilisée')),
                ('usage_date', models.DateField(verbose_name="Date d'utilisation")),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence (commande, facture)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='customers.productsubscription', verbose_name='Abonnement')),
            ],
            options={
                'verbose_name': "Utilisation d'abonnement",
                'verbose_name_plural': "Utilisations d'abonnements",
                'ordering': ['-usage_date'],
            },
        ),
        migrations.AddField(
            model_name='productsubscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='productsubscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit'),
        ),
        migrations.AlterUniqueTogether(
            name='productsubscription',
            unique_together={('customer', 'product')},
        ),
    ]
