# Generated by Django 4.2.7 on 2025-06-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom/Raison sociale')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne de contact')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Adresse ligne 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('services_provided', models.TextField(blank=True, verbose_name='Services fournis')),
                ('rc', models.CharField(blank=True, max_length=20, verbose_name='RC')),
                ('nis', models.CharField(blank=True, max_length=20, verbose_name='NIS')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('payment_terms', models.IntegerField(default=30, verbose_name='Délai de paiement (jours)')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Évaluation')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Date début contrat')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Date fin contrat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='customers.city', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
    ]
