# Generated by Django 4.2.7 on 2025-06-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('business_description', models.CharField(blank=True, max_length=300, verbose_name="Description d'activité")),
                ('address_line1', models.CharField(max_length=200, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Adresse ligne 2')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('capital_social', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Capital social')),
                ('rc', models.CharField(blank=True, max_length=50, verbose_name='RC (Registre de Commerce)')),
                ('art', models.CharField(blank=True, max_length=50, verbose_name='ART')),
                ('nis', models.CharField(blank=True, max_length=50, verbose_name='NIS')),
                ('nif', models.CharField(blank=True, max_length=50, verbose_name='NIF')),
                ('rib', models.CharField(blank=True, max_length=50, verbose_name='RIB')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('tva_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('timbre_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Timbre fiscal')),
                ('invoice_prefix', models.CharField(default='FACT', max_length=10, verbose_name='Préfixe facture')),
                ('next_invoice_number', models.PositiveIntegerField(default=1, verbose_name='Prochain numéro de facture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='customers.city', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
    ]
