# Generated by Django 5.2.4 on 2025-09-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='timbre_fiscal',
        ),
    ]
